global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_app'
    static_configs:
      - targets: 
        - 'host.docker.internal:3001'
  - job_name: 'log_scraper'
    static_configs:
      - targets: 
        - 'host.docker.internal:3002'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'host.docker.internal:9093'

rule_files:
  - "alert.rules.yml"






